### ISSUE TITLE
Add a binary file for the CC2538

### ISSUE THREAD

**Issue by bradjc** [lab11/IntelEdisonGateway#1]
@higherkuo could you commit a binary for the CC2538 on the gateway and the command line needed to flash it onto the gateway. We need to have that to commission new gateways.

**Comment by higherkuo** [comment]
committed.
The cc2538 can be flashed using BSL script `python2 cc2538-bsl.py -b 115200 -e -w -v  triumviMain.bin`
The source file can be found at: https://github.com/lab11/G2/tree/master/contiki/apps/edisonRX
